version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: django_Cartography_DB
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cartographyDjango
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8004:80"
    env_file:
      - .env

volumes:
  data:
